package com.darkmessage.app.ui.theme

import androidx.compose.ui.graphics.Color

// Dark theme colors — deep charcoal with blue accent
val DarkPrimary = Color(0xFF90CAF9)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFF00497D)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF263141)
val DarkSecondaryContainer = Color(0xFF3C4858)
val DarkOnSecondaryContainer = Color(0xFFD7E3F8)
val DarkTertiary = Color(0xFFD5BDE5)
val DarkOnTertiary = Color(0xFF392A48)
val DarkTertiaryContainer = Color(0xFF504060)
val DarkOnTertiaryContainer = Color(0xFFF1DAFF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0E1117)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF0E1117)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
val DarkOutline = Color(0xFF8D9199)
val DarkSurfaceContainer = Color(0xFF1A1D24)
val DarkSurfaceContainerHigh = Color(0xFF252830)
val DarkSurfaceContainerHighest = Color(0xFF30333B)

// Light theme colors
val LightPrimary = Color(0xFF1A6DB0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF535F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E3F8)
val LightOnSecondaryContainer = Color(0xFF101C2B)
val LightTertiary = Color(0xFF6B5778)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF1DAFF)
val LightOnTertiaryContainer = Color(0xFF251432)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFCFCFF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFCFCFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFDFE2EB)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightSurfaceContainer = Color(0xFFF0F0F4)
val LightSurfaceContainerHigh = Color(0xFFEAEAEE)
val LightSurfaceContainerHighest = Color(0xFFE4E4E8)
